### ISSUE TITLE
Refactor gfs_fetch for ftp fallback

### ISSUE THREAD

**Issue by SettRaziel** [SettRaziel/wrf_archlinux#122]
With the introduction of http checks with (#84) and the [diff](https://github.com/SettRaziel/wrf_archlinux/commit/05d86d53402b79ee6a43a17eb7f4156c62b674fe#diff-60f738266053cd615365981423a23d7350182e6145d7ab1536a48e479f3c76fe) in the gfs_fetch script, the ftp fallback can only be activated when applying the revert of the changes.
Since the https connections grows more unstable at the moment, the fallback option should possible. Also it should be checked if the protocol can be changed to ftps which would also lead to an encrypted connection and a valid transfer option.

**Comment by AnsgarSchmidt** [comment]
works, thanks

**Comment by SettRaziel** [comment]
Done with #124.
