### ISSUE TITLE
error compiling jaspber

### ISSUE THREAD

**Issue by AnsgarSchmidt** [SettRaziel/wrf_archlinux#24]
Making all in base
make[3]: Entering directory '/home/builduser/<wrf/jasper-1.900.2/src/libjasper/base'
/bin/sh ../../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../../src/libjasper/include/jasper  -I../../../src/libjasper/include -I/usr/include/tirpc -I/home/builduser/<wrf/libraries/netcdf/include  -g -O2 -MT jas_cm.lo -MD -MP -MF .deps/jas_cm.Tpo -c -o jas_cm.lo jas_cm.c
/bin/sh ../../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../../src/libjasper/include/jasper  -I../../../src/libjasper/include -I/usr/include/tirpc -I/home/builduser/<wrf/libraries/netcdf/include  -g -O2 -MT jas_debug.lo -MD -MP -MF .deps/jas_debug.Tpo -c -o jas_debug.lo jas_debug.c
/bin/sh: wrf/libraries/netcdf/include: No such file or directory
make[3]: *** [Makefile:467: jas_cm.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
/bin/sh: wrf/libraries/netcdf/include: No such file or directory
make[3]: *** [Makefile:467: jas_debug.lo] Error 1
make[3]: Leaving directory '/home/builduser/<wrf/jasper-1.900.2/src/libjasper/base'
make[2]: *** [Makefile:582: all-recursive] Error 1
make[2]: Leaving directory '/home/builduser/<wrf/jasper-1.900.2/src/libjasper'
make[1]: *** [Makefile:420: all-recursive] Error 1
make[1]: Leaving directory '/home/builduser/<wrf/jasper-1.900.2/src'
make: *** [Makefile:463: all-recursive] Error 1

**Comment by SettRaziel** [comment]
Can you give me additional configuration parameter, e.g. WRF3/4, Shell parameter, used liberaries?
The path to the netcdf package could not be found by the jasper library. Most of the time i got that when i did not set the correct library path.
I can try to run the install scripts within my test environment when i get your configuration paramter.

**Comment by AnsgarSchmidt** [comment]
Hi, thanks for the very fast answer, especially during the camp.

I used a newly installed arch Linux and run your install script.
 (Docker container with archlinux/base:latest)

pacman -Syy
pacman -Syu --noconfirm
pacman -S --noconfirm git sudo base-devel

useradd builduser -m
passwd -d builduser 
printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers
sudo -u builduser bash 

git clone https://github.com/SettRaziel/wrf_archlinux.git
cd wrf_archlinux/wrf_install/
./install_wrf.sh

Thanks again,
Ansgar

**Comment by SettRaziel** [comment]
I think i found the problem. At the moment you still need some manual work to set a working BUILD_PATH (detais here: https://github.com/SettRaziel/wrf_archlinux/tree/development/wrf_install). The current dummy value BUILD_PATH="<wrf path>" is reflected partially in your stacktrace, so i think making a branch in the fork with that parameter set to the value should address that issue.
I have created a ticket for that (#26 ) to fix this in the future.

**Comment by AnsgarSchmidt** [comment]
Hi,
it worked. And I am really sorry I did not read the instructions carefully enough. Thank you very much for your help and this awesome project.
