### ISSUE TITLE
[BUG] install_wrf.sh -> configure: error: Fortran could not compile .f90 files

### ISSUE THREAD

**Issue by AnsgarSchmidt** [SettRaziel/wrf_archlinux#51]
**Describe the bug**
Current arch linux with the development branch.

Error at Installing hdf5: 

checking quadmath.h presence... yes
checking for quadmath.h... yes
checking maximum decimal precision for C... 33
checking if Fortran interface enabled... yes
checking whether we are using the GNU Fortran compiler... no
checking whether gfortran accepts -g... no
checking for Fortran flag to compile .f90 files... unknown
configure: error: Fortran could not compile .f90 files

The problem and a possible solution was discussed here:
   https://www.myroms.org/forum/viewtopic.php?t=2243

Thanks
Ansgar

**Comment by SettRaziel** [comment]
I did a full run with the pull request yesterday and also started and new installation run on my testing VMs. I could not / cannot reproduce the error.
I have an updated arch linux with the latest packages and started a default installation. Works without problem.
You need to provide more information.

**Comment by AnsgarSchmidt** [comment]
Hi,

ok, what else can I provide?

 △ ~/Downloads sudo pacman -Syu                                                                                                                                                                                                         
[sudo] password for ansi: 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
:: Starting full system upgrade...
 there is nothing to do

 ▲ ~/Downloads wget https://github.com/SettRaziel/wrf_archlinux/archive/development.zip                                                                                                                                                 
unzip development.zip
vim wrf_archlinux-development/wrf_install/install_wrf.sh
 (setting BUILD_PATH='worf")
./install_wrf.sh

checking quadmath.h presence... yes
checking for quadmath.h... yes
checking maximum decimal precision for C... 33
checking if Fortran interface enabled... yes
checking whether we are using the GNU Fortran compiler... no
checking whether gfortran accepts -g... no
checking for Fortran flag to compile .f90 files... unknown
configure: error: Fortran could not compile .f90 files

Software:
gcc (GCC) 9.2.0

Please tell me if I should dump some version information.

Greetings
Ansgar

**Comment by AnsgarSchmidt** [comment]
Hi, I found a way to reproduce the error with archlinux on docker.
Same result

docker run -it --rm archlinux

pacman -Sy base-devel vim vi mc wget sudo unzip
useradd ansi
passwd ansi
mkdir /home/ansi
chown ansi.ansi /home/ansi
visudo
su - ansi
wget https://github.com/SettRaziel/wrf_archlinux/archive/development.zip
unzip development.zip
cd wrf_archlinux-development/wrf_install/
vim install_wrf.sh (BUILD PATH)
./install_wrf.sh

checking for quadmath.h... yes
checking maximum decimal precision for C... 33
checking if Fortran interface enabled... yes
checking whether we are using the GNU Fortran compiler... no
checking whether gfortran accepts -g... no
checking for Fortran flag to compile .f90 files... unknown
configure: error: Fortran could not compile .f90 files
[ansi@3531f08bb9ea wrf_install]$

**Comment by SettRaziel** [comment]
> checking whether we are using the GNU Fortran compiler... no

This looks like no gfortran is available. Since it is not in the gcc package nor in the base-devel it should not be in the docker container. You need to install gcc-fortran separately. What does pacman -Q gcc-fortran say?

**Comment by AnsgarSchmidt** [comment]
error: package 'gcc-fortran' was not found

Problem solved. Waiting for the update to test it further. :-)

Greetings
Ansgar

**Comment by SettRaziel** [comment]
I assumed that a valid fortran compiler was present before starting the scripts, so i am not sure if that should be addressed with a bug release. I created a branch and added that as a dependency for installation and deployment. But for the run process it is mandatory to have all required libraries, so i added a note in the readme. The branch is mainly to do the required test runs, but for consistency i will release that as v0.4.2 and move the other fixes to a later release.

**Comment by SettRaziel** [comment]
Addressed with #52.
